import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight, BookOpen, CalendarDays, ChevronRight, Crown, Flame, History, Image, Landmark, Search, Shield, Sparkles, Swords, Trophy, Users, Video} from 'lucide-react';
import './style.css';

const LEAGUE_ID='1362293179977576448';
const API=`https://api.sleeper.app/v1/league/${LEAGUE_ID}`;

const fallbackManagers=['Puneetj1234','edwinj58','rrazd19','Fazils21','kjoshi99','tekulvrf28','gchen123','Anishw3','SDosi','shreydawg32','amneet','anirudhiyer20','arkiran23','Shamadarapu'];
const colors=['#d8ff52','#ff735c','#6bdcff','#ffc857','#a78bfa','#f98ad2'];

function monogram(name='?'){return name.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()}
function Avatar({name,i=0}){return <span className="avatar" style={{'--tone':colors[i%colors.length]}}>{monogram(name)}</span>}

function App(){
 const [data,setData]=useState(null); const [view,setView]=useState('home'); const [query,setQuery]=useState('');
 useEffect(()=>{Promise.all([fetch(API).then(r=>r.json()),fetch(`${API}/users`).then(r=>r.json()),fetch(`${API}/rosters`).then(r=>r.json())]).then(([league,users,rosters])=>setData({league,users,rosters})).catch(()=>setData({league:{name:'Green Fn Dynasty',season:'2026',status:'in_season'},users:fallbackManagers.map((display_name,i)=>({display_name,user_id:String(i)})),rosters:[]}))},[]);
 const managers=useMemo(()=>{if(!data)return []; const byId=Object.fromEntries(data.users.map(u=>[u.user_id,u])); const linked=data.rosters.map(r=>{const u=byId[r.owner_id]||data.users.find(x=>(r.co_owners||[]).includes(x.user_id));return {name:u?.display_name||'Open roster',team:u?.metadata?.team_name||`Roster ${r.roster_id}`,roster:r.roster_id,players:r.players?.length||0}}); return (linked.length?linked:data.users.map((u,i)=>({name:u.display_name,team:u.metadata?.team_name||`Franchise ${i+1}`,roster:i+1,players:0}))).filter(x=>(x.name+' '+x.team).toLowerCase().includes(query.toLowerCase()))},[data,query]);
 const pages={home:<Home managers={managers}/>,history:<HistoryPage/>,managers:<Managers managers={managers} query={query} setQuery={setQuery}/>,trades:<Trades/>,vault:<Vault/>};
 return <div className="app">
  <header><button className="brand" onClick={()=>setView('home')}><span className="mark">GF</span><span><b>GREEN FN</b><small>DYNASTY ARCHIVE</small></span></button><nav>{[['home','Home'],['history','History'],['managers','Managers'],['trades','Trade Hall'],['vault','The Vault']].map(([id,label])=><button className={view===id?'active':''} onClick={()=>setView(id)} key={id}>{label}</button>)}</nav><div className="live"><i/> 2026 LIVE</div></header>
  <main>{pages[view]}</main>
  <footer><div><span className="mark">GF</span><b>Built for the league. Kept for the lore.</b></div><span>ESPN ERA â†’ SLEEPER DYNASTY Â· EST. YEAR TBD</span></footer>
 </div>
}

function Home({managers}){return <>
 <section className="hero"><div className="eyebrow"><Sparkles size={14}/> THE NEW ERA BEGINS</div><h1>Every season.<br/><em>Every story.</em></h1><p>The permanent record of Green Fn Dynastyâ€”where the old ESPN battles meet a new Sleeper dynasty.</p><div className="heroActions"><button className="primary" onClick={()=>document.querySelector('#standings').scrollIntoView({behavior:'smooth'})}>Meet the league <ChevronRight size={17}/></button><a href={`https://sleeper.com/leagues/${LEAGUE_ID}`} target="_blank">Open in Sleeper <ArrowUpRight size={15}/></a></div><div className="scorebug"><small>CURRENT ERA</small><b>14</b><span>FRANCHISES</span><hr/><b>2026</b><span>INAUGURAL DYNASTY SEASON</span></div></section>
 <section className="ticker"><span>LEAGUE WIRE</span><marquee>ROOKIE DRAFT COMPLETE&nbsp;&nbsp;â—†&nbsp;&nbsp;THE DYNASTY ERA IS OFFICIALLY UNDERWAY&nbsp;&nbsp;â—†&nbsp;&nbsp;14 TEAMS. ONE FOREVER TROPHY.&nbsp;&nbsp;â—†&nbsp;&nbsp;ARCHIVE SUBMISSIONS OPEN</marquee></section>
 <section className="intro"><div><span className="kicker">THE STORY SO FAR</span><h2>A redraft past.<br/>A dynasty future.</h2></div><div><p>Years of ESPN seasons built the rivalries. In 2026, the league moved to Sleeper and made every decision permanent. This is where the complete story lives.</p><div className="era"><span><b>01</b><small>THE ESPN YEARS</small><strong>REDRAFT ERA</strong></span><i/><span><b>02</b><small>2026 â†’ FOREVER</small><strong>DYNASTY ERA</strong></span></div></div></section>
 <section className="featureGrid"><article className="feature lime"><History/><small>LEAGUE HISTORY</small><h3>Seasons that made us</h3><p>Champions, standings, heartbreaks, and the games decided by hundredths.</p><span>Archive awaiting ESPN import <ChevronRight size={16}/></span></article><article className="feature orange"><Swords/><small>TRADE HALL</small><h3>Deals that changed everything</h3><p>The bold, the brilliant, and the trades nobody will ever let you forget.</p><span>Nominate a trade <ChevronRight size={16}/></span></article><article className="feature blue"><Video/><small>THE VAULT</small><h3>Receipts preserved</h3><p>Punishment videos, screenshots, draft-night photos, and permanent evidence.</p><span>Media intake coming next <ChevronRight size={16}/></span></article></section>
 <section id="standings" className="rosterBand"><div className="sectionHead"><div><span className="kicker">FOUNDING DYNASTY CLASS</span><h2>The franchises</h2></div><span>Live from Sleeper Â· {managers.length} rosters</span></div><div className="managerStrip">{managers.slice(0,7).map((m,i)=><div className="mini" key={m.roster}><Avatar name={m.team} i={i}/><b>{m.team}</b><span>@{m.name}</span></div>)}</div></section>
 </>}

function HistoryPage(){return <Page title="League History" label="THE RECORD BOOK" sub="Every champion, every finish, every seasonâ€”from the ESPN redraft years into the dynasty era."><div className="timeline"><div className="year current"><b>2026</b><span>DYNASTY ERA</span><h3>The reset that lasts forever</h3><p>Green Fn moves to Sleeper. Fourteen franchises begin building for the long haul.</p></div><div className="year muted"><b>20??â€“2025</b><span>ESPN ERA</span><h3>The original chapters</h3><p>Season records will appear here after the historical ESPN export is connected.</p><button><BookOpen size={16}/> Import archive</button></div></div><Empty icon={Trophy} title="The trophy case needs its plaques" text="Send the ESPN season IDs (and access cookies if private) to populate champions, standings, records, and playoff brackets."/></Page>}
function Managers({managers,query,setQuery}){return <Page title="The Managers" label="14 FRANCHISES. ZERO PEACE." sub="Career profiles that grow with every seasonâ€”highs, lows, signature players, and lasting grudges."><label className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search manager or franchise"/></label><div className="managerGrid">{managers.map((m,i)=><article key={m.roster}><Avatar name={m.team} i={i}/><small>FRANCHISE {String(m.roster).padStart(2,'0')}</small><h3>{m.team}</h3><p>@{m.name}</p><div><span><b>2026</b><small>JOINED DYNASTY</small></span><span><b>{m.players||'â€”'}</b><small>ROSTERED</small></span><span><b>â€”</b><small>BEST FINISH</small></span></div></article>)}</div></Page>}
function Trades(){return <Page title="Trade Hall" label="FORTUNES WERE EXCHANGED" sub="A living museum of the leagueâ€™s most lopsided, legendary, and league-altering deals."><div className="award"><Landmark size={28}/><span>INAUGURAL CLASS</span><h2>Who belongs in the Trade Hall?</h2><p>Nominate a deal with the date, both sides, the argument for induction, and any screenshots. Community voting can be added once the first class is assembled.</p><button>Submit the first trade <ArrowUpRight size={16}/></button></div><Empty icon={Swords} title="No legends without receipts" text="Historical ESPN trades aren't exposed in the response we can access yet. Sleeper trades will be captured automatically once the season begins."/></Page>}
function Vault(){return <Page title="The Vault" label="PROOF OR IT DIDN'T HAPPEN" sub="Punishments, photo evidence, videos, screenshots, and artifacts from the league group chat."><div className="vaultGrid"><div className="vaultCard"><Video/><span>VIDEO</span><h3>Punishment tapes</h3><p>The leagueâ€™s most important film archive.</p></div><div className="vaultCard"><Image/><span>SCREENSHOTS</span><h3>Photo finishes</h3><p>Including every 0.04-point nightmare.</p></div><div className="vaultCard"><Flame/><span>LORE</span><h3>Group chat canon</h3><p>Cold takes preserved for future generations.</p></div></div><Empty icon={Shield} title="The vault is ready" text="Upload the first batch of photos, videos, and screenshots and theyâ€™ll be organized by season, matchup, and manager."/></Page>}
function Page({title,label,sub,children}){return <><section className="pageHero"><span className="kicker">{label}</span><h1>{title}</h1><p>{sub}</p></section><section className="pageBody">{children}</section></>}
function Empty({icon:Icon,title,text}){return <div className="empty"><Icon/><div><h3>{title}</h3><p>{text}</p></div><ChevronRight/></div>}
createRoot(document.getElementById('root')).render(<App/>);

